/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.udistrital.bdd.visual;

import dependenciasfuncionales.DependenciasFuncionales;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.ArrayList;
import java.util.Map;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author jcifuentesz
 */
public class FrameDependencias extends javax.swing.JFrame {

    /**
     * Creates new form FrameDependencias
     */
    public FrameDependencias() {
        initComponents();
    }
    File fichero;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInfo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        filename = new javax.swing.JTextField();
        botonCargar = new javax.swing.JButton();
        paneAtributos = new javax.swing.JPanel();
        btnCarga = new javax.swing.JButton();
        panelCabecera = new javax.swing.JPanel();
        panelRelaciones = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        CrearRelaciones = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelInfo.setBackground(new java.awt.Color(51, 0, 51));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ATRIBUTOS");
        jLabel1.setAutoscrolls(true);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("RELACIONES");
        jLabel2.setAutoscrolls(true);

        botonCargar.setText("BUSCAR");
        botonCargar.addActionListener(new ActionListener(){

            @Override
            public void actionPerformed(ActionEvent e) {
                JFileChooser fc=new JFileChooser();
                int seleccion=fc.showOpenDialog(panelInfo);
                if(seleccion==JFileChooser.APPROVE_OPTION){
                    fichero=fc.getSelectedFile();
                    filename.setText(fichero.getAbsolutePath());
                }
            }

        });

        paneAtributos.setBackground(new java.awt.Color(51, 0, 51));
        paneAtributos.setLayout(new java.awt.GridLayout(0, 2));

        btnCarga.setText("CARGAR");
        btnCarga.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if(fichero==null){
                    JOptionPane.showMessageDialog(null, "EL ARCHIVO ES NULO, NO SEA GUEVON", "MALPARIDO BOBO!!", JOptionPane.PLAIN_MESSAGE);
                }else{
                    Map<String, String> mapDatos=DependenciasFuncionales.leertxt(fichero);
                    ArrayList<String> atributos = DependenciasFuncionales.obtenerElementosMap(mapDatos, "T");
                    ArrayList<String> relaciones = DependenciasFuncionales.obtenerElementosMap(mapDatos, "L");
                    crearDependenciasRelaciones(atributos,relaciones);
                }
            }
        });

        javax.swing.GroupLayout panelInfoLayout = new javax.swing.GroupLayout(panelInfo);
        panelInfo.setLayout(panelInfoLayout);
        panelInfoLayout.setHorizontalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paneAtributos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelInfoLayout.createSequentialGroup()
                        .addComponent(filename, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelInfoLayout.createSequentialGroup()
                        .addComponent(botonCargar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCarga)))
                .addContainerGap())
        );
        panelInfoLayout.setVerticalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneAtributos, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCargar)
                    .addComponent(btnCarga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelCabecera.setForeground(new java.awt.Color(255, 255, 255));
        panelCabecera.setLayout(new java.awt.GridLayout(0, 3));

        panelRelaciones.setBackground(new java.awt.Color(102, 102, 102));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ATRIBUTOS IMPLICANTES");
        jLabel3.setAutoscrolls(true);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("RELACIONES");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ATRIBUTOS IMPLICADOS");

        javax.swing.GroupLayout panelRelacionesLayout = new javax.swing.GroupLayout(panelRelaciones);
        panelRelaciones.setLayout(panelRelacionesLayout);
        panelRelacionesLayout.setHorizontalGroup(
            panelRelacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRelacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 246, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(207, 207, 207)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        panelRelacionesLayout.setVerticalGroup(
            panelRelacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRelacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRelacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        CrearRelaciones.setText("Crear relaciones");
        CrearRelaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearRelacionesActionPerformed(evt);
            }
        });
        jMenu1.add(CrearRelaciones);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelRelaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCabecera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelRelaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelCabecera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearRelacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearRelacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CrearRelacionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameDependencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameDependencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameDependencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameDependencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameDependencias().setVisible(true);
            }
        });
    }
    
    private void crearDependenciasRelaciones(ArrayList<String> atributos,ArrayList<String> relaciones){
        ArrayList<JButton> botones = new ArrayList<>();
        int contador = atributos.size()>relaciones.size()?atributos.size():relaciones.size();
        for(int i=0; i<contador;i++){
            JButton btnRel = new JButton();
            JButton btnAtr = new JButton();
            javax.swing.JLabel jtxxFld = new javax.swing.JLabel();
            if(i<atributos.size()){
                btnAtr.setText(atributos.get(i));
                paneAtributos.add(btnAtr);
            }else{
                jtxxFld = new javax.swing.JLabel();
                jtxxFld.setText("");
                paneAtributos.add(jtxxFld);
            }
            if(i<relaciones.size()){
                btnRel.setText(relaciones.get(i));
                paneAtributos.add(btnRel);
            }else{
                jtxxFld = new javax.swing.JLabel();
                jtxxFld.setText("");
                paneAtributos.add(jtxxFld);
            }
            
        }
        paneAtributos.updateUI();
        for(String rel:relaciones){
            System.out.println("rel: "+rel);
            System.out.println("implicado "+rel.split("->")[1]);
            System.out.println("implicante "+rel.split("->")[0]);
            JButton implicado = new JButton();
            JButton implicante = new JButton();
            JButton relacion = new JButton();
            relacion.setText(rel);
            implicado.setText(rel.split("->")[0]);
            
            implicante.setText(rel.split("->")[1]);
            panelCabecera.add(implicado);
            panelCabecera.add(relacion);
            panelCabecera.add(implicante);
            javax.swing.JLabel jtxxFld = new javax.swing.JLabel();
            jtxxFld.setText("");
             javax.swing.JLabel jtxxFld1 = new javax.swing.JLabel();
            jtxxFld1.setText("");
             javax.swing.JLabel jtxxFld2 = new javax.swing.JLabel();
            jtxxFld2.setText("");
            panelCabecera.add(jtxxFld);
            panelCabecera.add(jtxxFld1);
            panelCabecera.add(jtxxFld2);
        }
        panelCabecera.updateUI();
//                ,panelRelaciones
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CrearRelaciones;
    private javax.swing.JButton botonCargar;
    private javax.swing.JButton btnCarga;
    private javax.swing.JTextField filename;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel paneAtributos;
    private javax.swing.JPanel panelCabecera;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JPanel panelRelaciones;
    // End of variables declaration//GEN-END:variables
}
